version: '3'

services:
  ganache:
    container_name: ganache
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"

  app:
    build: ./app
    command: yarn dev
    container_name: app
    volumes:
      - ./app:/usr/app
    ports:
      - "3000:3000"
    depends_on:
      - ganache
