version: '3'

services:
  ganache:
    container_name: ganache
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"

  app:
    build: .
    command: npm run dev
    container_name: app
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - ganache
